packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
